name: CI/CD Pipeline

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: shoeshop
  CONTAINER_NAME: shoeshop
  DOCKER_IMAGE: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/shoeshop:${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push Image
        run: docker push $DOCKER_IMAGE

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Login Docker
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull Image
        run: docker pull $DOCKER_IMAGE

      - name: Remove old container
        run: docker rm -f $CONTAINER_NAME || true

      - name: Run container
        run: docker run -d -p 8080:8080 --name $CONTAINER_NAME $DOCKER_IMAGE

  show-log:
    runs-on: self-hosted
    needs: deploy

    steps:
      - run: sleep 20
      - run: docker logs $CONTAINER_NAME
